name: front
description: "The frontend of the evaluation JO project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.10
  auto_route: ^7.8.4
  gap: ^3.0.1
  url_strategy: ^0.2.0
  dart_jsonwebtoken: ^2.13.0
  google_fonts: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/